pluginGroup=com.jacemayer.dclass
pluginVersion=0.0.1

localIdePath=/Applications/PyCharm.app

platformVersion=2026.2.1

org.gradle.java.installations.paths=/usr/local/opt/openjdk@25/libexec/openjdk.jdk/Contents/Home,/usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home
org.gradle.jvmargs=-Xmx2048m
org.gradle.caching=true
kotlin.stdlib.default.dependency=false
