package com.jacemayer.dclass.python

import com.intellij.ide.fileTemplates.FileTemplateManager
import com.intellij.ide.fileTemplates.FileTemplateUtil
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.actionSystem.LangDataKeys
import com.intellij.openapi.command.WriteCommandAction
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.DialogWrapper
import com.intellij.openapi.ui.ValidationInfo
import com.intellij.psi.PsiDirectory
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiFile
import com.intellij.psi.PsiManager
import com.intellij.ui.components.JBCheckBox
import com.intellij.ui.components.JBLabel
import com.intellij.ui.components.JBTextField
import com.intellij.ui.dsl.builder.panel
import com.intellij.util.ui.JBUI
import com.jacemayer.dclass.python.DCDistributedClassNames.Side
import javax.swing.JComponent
import javax.swing.event.DocumentEvent
import javax.swing.event.DocumentListener

class DCNewDistributedClassAction : AnAction() {

    override fun getActionUpdateThread(): ActionUpdateThread = ActionUpdateThread.BGT

    override fun update(e: AnActionEvent) {
        e.presentation.isEnabledAndVisible = e.project != null && targetDirectory(e) != null
    }

    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val directory = targetDirectory(e) ?: return

        val dialog = DCNewDistributedClassDialog(project)
        if (!dialog.showAndGet()) return

        val created = create(project, directory, dialog.typedName, dialog.isGlobal, dialog.sides)
        created.firstOrNull()?.let { file ->
            file.virtualFile?.let { com.intellij.openapi.fileEditor.FileEditorManager.getInstance(project).openFile(it, true) }
        }
    }

    private fun create(
        project: Project,
        directory: PsiDirectory,
        typed: String,
        global: Boolean,
        sides: List<Side>,
    ): List<PsiFile> {
        val manager = FileTemplateManager.getInstance(project)
        return WriteCommandAction.writeCommandAction(project)
            .withName("Create Distributed Class")
            .compute<List<PsiFile>, RuntimeException> {
                sides.mapNotNull { side ->
                    val templateName = DCDistributedClassNames.baseClass(global, side)
                    val template = manager.getInternalTemplate(templateName)
                    val properties = manager.defaultProperties
                    val fileName = DCDistributedClassNames.className(typed, global, side)
                    FileTemplateUtil.createFromTemplate(template, fileName, properties, directory)
                        as? PsiFile
                }
            }
    }

    private fun targetDirectory(e: AnActionEvent): PsiDirectory? {
        e.getData(LangDataKeys.IDE_VIEW)?.orChooseDirectory?.let { return it }
        val element = e.getData(CommonDataKeys.PSI_ELEMENT) as? PsiElement
        (element as? PsiDirectory)?.let { return it }
        (element as? PsiFile)?.containingDirectory?.let { return it }
        val file = e.getData(CommonDataKeys.VIRTUAL_FILE) ?: return null
        val project = e.project ?: return null
        val directory = if (file.isDirectory) file else file.parent ?: return null
        return PsiManager.getInstance(project).findDirectory(directory)
    }
}

class DCNewDistributedClassDialog(project: Project) : DialogWrapper(project) {

    private val nameField = JBTextField(24)
    private val globalBox = JBCheckBox("Global object")
    private val clientBox = JBCheckBox("Client", true)
    private val aiBox = JBCheckBox("AI", true)
    private val udBox = JBCheckBox("UD", false)
    private val preview = JBLabel()

    val typedName: String get() = nameField.text.trim()
    val isGlobal: Boolean get() = globalBox.isSelected

    val sides: List<Side>
        get() = buildList {
            if (clientBox.isSelected) add(Side.CLIENT)
            if (aiBox.isSelected) add(Side.AI)
            if (udBox.isSelected) add(Side.UD)
        }

    init {
        title = "New Distributed Class"
        setOKButtonText("Create")

        val refresh = { updatePreview() }
        nameField.document.addDocumentListener(object : DocumentListener {
            override fun insertUpdate(e: DocumentEvent) = refresh()
            override fun removeUpdate(e: DocumentEvent) = refresh()
            override fun changedUpdate(e: DocumentEvent) = refresh()
        })
        for (box in listOf(globalBox, clientBox, aiBox, udBox)) box.addActionListener { refresh() }

        globalBox.toolTipText =
            "A global object is generated by the repository rather than constructed, " +
                "and is written without the Distributed prefix."

        init()
        updatePreview()
    }

    override fun getPreferredFocusedComponent(): JComponent = nameField

    override fun createCenterPanel(): JComponent = panel {
        row("Name:") { cell(nameField) }
        row("") { cell(globalBox) }
        row("Sides:") {
            cell(clientBox)
            cell(aiBox)
            cell(udBox)
        }
        row("") { cell(preview) }
    }.apply { border = JBUI.Borders.empty(8, 8, 4, 8) }

    private fun updatePreview() {
        val name = typedName
        val chosen = sides
        val text = when {
            DCDistributedClassNames.validate(name, isGlobal) != null || chosen.isEmpty() -> " "
            else -> chosen.joinToString("<br>") {
                DCDistributedClassNames.fileName(name, isGlobal, it)
            }
        }
        preview.text = "<html><body style='color:#808080'>$text</body></html>"
    }

    override fun doValidate(): ValidationInfo? {
        DCDistributedClassNames.validate(typedName, isGlobal)?.let {
            return ValidationInfo(it, nameField)
        }
        if (sides.isEmpty()) return ValidationInfo("Choose at least one side", clientBox)
        return null
    }
}
